# Runs all unit-tests.
# The examples are run as part of the coverage workflow.
name: Tests

defaults:
  run:
    shell: bash

on:  # Runs on any push event to any branch except master (the coverage workflow takes care of that)
  push:
    branches-ignore:
      - 'master'

jobs:
  tests:
    uses: pylhc/.github/.github/workflows/tests.yml@master
    with:
      pytest-options: -m "not example"

#   examples:
#     needs: tests
#     uses: pylhc/.github/.github/workflows/tests.yml@master
#     with:
#       pytest-options: -m "example"
