# Runs all tests
name: Tests

defaults:
  run:
    shell: bash

on:  # Runs on any push event to any branch except master (the coverage workflow takes care of that)
    workflow_dispatch
#   push:
#     branches-ignore:
#       - 'master'

jobs:
  tests:
    uses: pylhc/.github/.github/workflows/tests.yml@master
    with:
      pytest-options: -m "not example"

  examples:
    needs: tests
    uses: pylhc/.github/.github/workflows/tests.yml@master
    with:
      pytest-options: -m "example"
